// @context-towel/ui - Unified UI package
//
// Sibling packages (@context-towel/card-library, @context-towel/context-graph,
// @context-towel/markdown) should be imported directly by consumers.
// This package exports NEW ui modules only.

// --- Prompt Builder (ct-9) ---
export {
  // Types
  type TemplateVariable,
  type VersionedTemplate,
  type SystemPrompt,
  type VariableDefinition,
  type VariableValue,
  type CodeIndexerRule,
  type ProjectInfo,
  type PromptChainTemplate,
  type RulesProvider,
  type TemplateCategory,
  TEMPLATE_CATEGORIES,
  // Context & Provider
  PromptBuilderProvider,
  usePromptBuilderStore,
  usePromptPort,
  useRulesProvider,
  type PromptBuilderProviderProps,
  type PromptManagementPort,
  // Store
  createPromptBuilderStore,
  type PromptBuilderState,
  type PromptBuilderSnapshot,
  type PromptBuilderActions,
  // Components
  PromptBuilder,
  type PromptBuilderProps,
  VariableEditor,
  type VariableEditorProps,
  VariableInput,
  type VariableInputProps,
  QuickTemplateSelector,
  type QuickTemplateSelectorProps,
  TemplateList,
  type TemplateListProps,
  // Services
  composePrompt,
  buildRulesPrompt,
  type PromptCompositionConfig,
  type PromptCompositionResult,
  createVariable,
  updateVariable,
  deleteVariable,
  getVariableValues,
  setVariableValues,
  getCombinedValues,
  getVariablesByScope,
  fillTemplate,
  getPresetTemplates,
  mergeTemplates,
  createTemplate,
  duplicateTemplate,
  createEmptyDraft,
  fillVersionedTemplate,
  normalizeCategory,
  // Utils
  validateTemplate,
  validateTemplates,
  sanitizeTemplate,
  generateTemplateId,
  isTemplateSafe,
  createSafeTemplate,
  type ValidationResult,
  type SystemPromptTemplate,
  exportTemplates,
  downloadTemplates,
  importTemplates,
  readFileAsText,
  validateImportFile,
  exportTemplatesFile,
  parseTemplateImport,
  type TemplateExportData,
  type ImportResult,
  // Presets
  PRESET_TEMPLATES,
} from './prompt-builder'
