import { defineConfig } from 'tsup'

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    'react/jsx-runtime',
    'react/jsx-dev-runtime',
    '@context-towel/card-library',
    '@milkdown/core',
    '@milkdown/ctx',
    '@milkdown/preset-commonmark',
    '@milkdown/preset-gfm',
    '@milkdown/prose',
    '@milkdown/react',
    '@milkdown/transformer',
    '@milkdown/utils',
    '@milkdown/plugin-listener',
    '@milkdown/plugin-slash',
    '@milkdown/plugin-block',
    '@milkdown/plugin-history',
    '@floating-ui/dom',
    'mermaid',
    'highlight.js',
    'emoji-dictionary',
    'katex',
    'katex/contrib/auto-render',
    'unist-util-visit',
  ],
})
